# 🧮 NumPy  — Student Workbook

---

**Duration:** 1.5 Hours  
**Topic:** NumPy — Numerical Computing with Python  
**Level:** Easy → Medium  

---

### 📋 Instructions
- Write your answers in the **blank code cells** below each task.
- Do **not** modify the task description cells.
- Run each cell after writing your answer to verify it works.
- Import NumPy at the start — it is already done for you below.

---

In [14]:
import numpy as np
print('NumPy version:', np.__version__)
print('✅ NumPy imported successfully!')

NumPy version: 1.26.4
✅ NumPy imported successfully!


---
## 🟢 SECTION 1 — Easy (Tasks 1–12)
---

### ✅ Task 1 — Create a 1D Array
Create a NumPy array from the following Python list:  
`[10, 20, 30, 40, 50]`  
Print the array and its **data type**.

In [18]:
# ✏️ Write your answer here
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

### ✅ Task 2 — Array of Zeros and Ones
1. Create an array of **5 zeros** (float type).
2. Create an array of **5 ones** (float type).
3. Print both arrays.

In [23]:
# ✏️ Write your answer here
zero = np.zeros(5)
one = np.ones(5)
zero

array([0., 0., 0., 0., 0.])

In [25]:
one

array([1., 1., 1., 1., 1.])

### ✅ Task 3 — Range Array with `arange`
Create an array of all **even numbers from 0 to 20** (inclusive) using `np.arange`.  
Print the result.

In [27]:
# ✏️ Write your answer here
b = np.arange(1,21)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### ✅ Task 4 — Linspace
Use `np.linspace` to create an array of **7 evenly spaced values** between `0` and `1`.  
Print the array.

In [31]:
# ✏️ Write your answer here
c = np.linspace(0,1,7)
c

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

### ✅ Task 5 — Array Shape and Dimensions
Create the following array and print its **shape**, **number of dimensions (ndim)**, and **total number of elements (size)**:
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
```

In [41]:
# ✏️ Write your answer here
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Shape = {arr.shape}")
print(f"Dimension = {arr.ndim}")
print(f"Size = {arr.size}")


Shape = (2, 3)
Dimension = 2
Size = 6


### ✅ Task 6 — Array Indexing
Given:
```python
arr = np.array([5, 15, 25, 35, 45, 55])
```
1. Print the **first** element.
2. Print the **last** element.
3. Print the element at index **3**.

In [43]:
# ✏️ Write your answer here
arr = np.array([5, 15, 25, 35, 45, 55])
print(f"First = {arr[0]}\nLast = {arr[-1]}\nThird index = {arr[3]}")


First = 5
Last = 55
Third index = 35


### ✅ Task 7 — Array Slicing
Given:
```python
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
```
1. Slice elements from index **2 to 5** (inclusive).
2. Slice the **last 3 elements**.
3. Slice every **other element** (step = 2).

In [45]:
# ✏️ Write your answer here
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
arr[2:6]

array([30, 40, 50, 60])

### ✅ Task 8 — Basic Math Operations
Given:
```python
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
```
Compute and print:
1. `a + b`
2. `b - a`
3. `a * b`
4. `b / a`

In [ ]:
# ✏️ Write your answer here


### ✅ Task 9 — Statistical Functions
Given:
```python
data = np.array([4, 7, 13, 2, 1, 9, 15, 6, 11, 8])
```
Calculate and print:
- **Mean**, **Median**, **Standard Deviation**, **Min**, **Max**

In [ ]:
# ✏️ Write your answer here


### ✅ Task 10 — Reshape an Array
Create an array using `np.arange(1, 13)` and reshape it into a **3×4 matrix**.  
Print the reshaped array and its shape.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 11 — Identity and Diagonal Matrix
1. Create a **4×4 identity matrix** using `np.eye`.
2. Extract only the **diagonal elements** from it using `np.diag`.
3. Print both.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 12 — Random Array
1. Set random seed to **42** for reproducibility.
2. Generate a **3×3 array** of random integers between **1 and 100** using `np.random.randint`.
3. Print the array.

In [ ]:
# ✏️ Write your answer here


---
## 🟡 SECTION 2 — Medium (Tasks 13–24)
---

### ✅ Task 13 — Boolean Masking
Given:
```python
scores = np.array([45, 78, 90, 32, 55, 88, 67, 23, 95, 40])
```
1. Create a boolean mask for all scores **greater than 60**.
2. Use the mask to extract only those scores.
3. Print the mask and the filtered scores.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 14 — Fancy Indexing
Given:
```python
arr = np.array([100, 200, 300, 400, 500, 600, 700])
```
Use **fancy indexing** to extract elements at indices `[0, 2, 4, 6]`.  
Then replace the element at index `1` with `999`.  
Print both results.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 15 — Stacking Arrays
Given:
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```
1. Stack them **vertically** using `np.vstack`. Print the result.
2. Stack them **horizontally** using `np.hstack`. Print the result.
3. Stack them using `np.column_stack`. Print the result.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 16 — Splitting Arrays
Create `arr = np.arange(1, 25)` and:
1. Split it into **4 equal parts** using `np.split`. Print each part.
2. Reshape it to `(4, 6)` and split into **2 arrays horizontally** using `np.hsplit`. Print both.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 17 — Broadcasting
Given:
```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row    = np.array([10, 20, 30])
```
1. Add `row` to every row of `matrix` using **broadcasting**. Print the result.
2. Multiply the entire `matrix` by scalar `5`. Print the result.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 18 — Sorting
Given:
```python
arr = np.array([3, 1, 9, 5, 2, 8, 4, 7, 6])
```
1. Sort the array in **ascending order**.
2. Sort in **descending order**.
3. Return the **indices that would sort** the array (`np.argsort`).
4. Find the index of the **maximum** and **minimum** values.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 19 — Aggregations Along Axes
Given:
```python
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
```
Calculate:
1. **Sum of each column** (axis=0)
2. **Mean of each row** (axis=1)
3. **Max of the entire matrix**
4. **Cumulative sum** of the flattened matrix

In [ ]:
# ✏️ Write your answer here


### ✅ Task 20 — `where` Condition
Given:
```python
grades = np.array([55, 82, 37, 90, 48, 73, 60, 29, 95, 67])
```
Use `np.where` to create a new array where:
- Grades **>= 60** become the string `'Pass'`
- Grades **< 60** become the string `'Fail'`

Print the result.

In [ ]:
# ✏️ Write your answer here


### ✅ Task 22 — Unique Values and Counting
Given:
```python
data = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 3, 3])
```
1. Find all **unique values**.
2. Find the **count of each unique value**.
3. Find the **index of first occurrence** of each unique value.
*(Use `np.unique` with appropriate parameters)*

In [ ]:
# ✏️ Write your answer here


### ✅ Task 23 — Flatten and Ravel
Given:
```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
```
1. Flatten using `.flatten()` — modify the returned array and check if original changes.
2. Flatten using `.ravel()` — modify the returned array and check if original changes.
3. Explain the difference (as a comment in your code).

In [ ]:
# ✏️ Write your answer here
